spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:56231}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    peer-node-connect-retry-delay-ms: 5000
  instance:
    prefer-ip-address: true
